#ifndef _DEFINE_H
#define _DEFINE_H

#include <ntddk.h>
#include <wdf.h>
#include <initguid.h>

#define DRIVER_NAME "MyKWDF1"
#define MEM_TAG '10hZ' // 内存标签

#define MSG_CODE_READ CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_OUT_DIRECT, FILE_READ_ACCESS)
#define MSG_CODE_WRITE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_IN_DIRECT, FILE_WRITE_ACCESS)
#define MSG_CODE_REQUEST_APP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_OUT_DIRECT, FILE_READ_ACCESS) // 驱动 -> 应用 请求APP
#define MSG_CODE_CMD_WRITE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_IN_DIRECT, FILE_WRITE_ACCESS) // 应用 -> 驱动 cmd任务

#define INT_MUL_8_MASK 0b0111ull
#define INT_MUL_8 (~INT_MUL_8_MASK)

typedef struct _INDEX {
	UINT64 key;
	void* value;
} INDEX, * PINDEX;

typedef struct _DISK_DEVICE_CONTEXT {
	UNICODE_STRING devName;
	UNICODE_STRING symlinkName;
	UINT64 id;
	WDFDEVICE dev;
	WDFQUEUE requestAppQueue;
	WDFQUEUE cmdQueue;
} DISK_DEVICE_CONTEXT, * PDISK_DEVICE_CONTEXT;

typedef struct _CTRL_DEVICE_CONTEXT {
	BOOLEAN isOpen;
	WDFSPINLOCK openLock; // 打开锁
	RTL_AVL_TABLE diskDevIndex; // 磁盘设备索引
	UINT64 diskDevIDSeq;
} CTRL_DEVICE_CONTEXT, * PCTRL_DEVICE_CONTEXT;

// {2392C289-E860-4B8A-A5FC-5891DDFD3B63}
DEFINE_GUID(GUID_CTRL_DEV,
	0x2392c289, 0xe860, 0x4b8a, 0xa5, 0xfc, 0x58, 0x91, 0xdd, 0xfd, 0x3b, 0x63);

// {14B91C2E-0241-404B-9664-05233AF6218C}
DEFINE_GUID(GUID_MY_DISK_DEV,
	0x14b91c2e, 0x241, 0x404b, 0x96, 0x64, 0x5, 0x23, 0x3a, 0xf6, 0x21, 0x8c);

#endif // !_DEFINE_H

